
class LLMResponse:
    _model: str
    _response: str

    """ -----------------------------------------------------------------------
    Summary:
        Cosntructs a new LLMResponse

    Parameters:
        model - the name of the model that generated the output.
        reponse - the response generated by the LLM.
    ----------------------------------------------------------------------- """ 
    def __init__(self, model: str, response: str) -> None:
        self._model = model
        self._response = response

    """ -----------------------------------------------------------------------
    Summary:
        Returns the name of the model for the reponse.

    Returns:
        Returns a string representing the name of the LLM that generated this
        reponse.
    ----------------------------------------------------------------------- """ 
    def model(self) -> str:
        return self._model
    
    """ -----------------------------------------------------------------------
    Summary:
        Returns the reponse text generated by the model.

    Returns:
        Returns a string containing the generated output.
    ----------------------------------------------------------------------- """ 
    def response(self) -> str:
        return self._response
    
    """ -----------------------------------------------------------------------
    Summary:
        Returns a dictionary representation of this object for easy 
        serialization.

    Returns:
        Returns a dictionary of the form 
        {"model"=self.model, "response"=self.response}.
    ----------------------------------------------------------------------- """ 
    def toDict(self) -> dict[str, str]:
        data: dict[str, str] = {}
        data["model"] = self._model
        data["response"] = self._response
        return data