import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import Image from "next/image";
import Button from "@mui/material/Button";
import React from "react";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Argo MutiLLM',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <div lang="en" style={{overflowX: "hidden"}}>
            <div style={{
                width: '100%',
                background: '#1f7cd3',
                height: '62px',
                position: "absolute",
                top: 0,
                left: 0,
                display: "flex",
                alignItems: "center",
                paddingLeft: "1rem",
                paddingRight: "1rem",
            }}>
                <a
                    className="pointer-events-none flex place-items-center gap-2 p-8 lg:pointer-events-auto lg:p-0"
                    href="https://argodata.com/"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    <Image
                        src="http://localhost:3000/argo.svg"
                        alt="argo logo"
                        style={{filter: 'brightness(0) invert(1)'}}
                        width={200}
                        height={40}
                        priority
                    />
                </a>
                <Button style={{color: "white", marginLeft: "auto", marginRight: '2rem'}}
                        variant="text">MultiLLM</Button>
            </div>
            <body style={{maxWidth: '100vw', background: 'white'}}>{children}</body>
        </div>
    )
}
