# Generated by Django 4.2.5 on 2023-11-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
